import type { Metadata } from "next";

import "./globals.css";

import Providers from "@/lib/providers/Providers";
import { redHatDisplay } from "@/components/theme";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${redHatDisplay.className}`}>
      <body className={`  antialiased`}>
        <Providers>
          <ToastContainer position="top-center" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
